# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interaction_manager/ui/dialogmainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogGUI(object):
    def setupUi(self, DialogGUI):
        DialogGUI.setObjectName("DialogGUI")
        DialogGUI.resize(1216, 753)
        DialogGUI.setAutoFillBackground(True)
        self.centralWidget = QtWidgets.QWidget(DialogGUI)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.designPanelLayout = QtWidgets.QGridLayout()
        self.designPanelLayout.setSpacing(6)
        self.designPanelLayout.setObjectName("designPanelLayout")
        self.tmpWidget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmpWidget.sizePolicy().hasHeightForWidth())
        self.tmpWidget.setSizePolicy(sizePolicy)
        self.tmpWidget.setObjectName("tmpWidget")
        self.designPanelLayout.addWidget(self.tmpWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.designPanelLayout, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 1, 1)
        DialogGUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DialogGUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1216, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuRobot = QtWidgets.QMenu(self.menuBar)
        self.menuRobot.setObjectName("menuRobot")
        self.menuDatabase = QtWidgets.QMenu(self.menuBar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        DialogGUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(DialogGUI)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.mainToolBar.setOrientation(QtCore.Qt.Horizontal)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        DialogGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(DialogGUI)
        self.statusBar.setObjectName("statusBar")
        DialogGUI.setStatusBar(self.statusBar)
        self.behavioralParametersDockWidget = QtWidgets.QDockWidget(DialogGUI)
        self.behavioralParametersDockWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.behavioralParametersDockWidget.sizePolicy().hasHeightForWidth())
        self.behavioralParametersDockWidget.setSizePolicy(sizePolicy)
        self.behavioralParametersDockWidget.setMinimumSize(QtCore.QSize(400, 550))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.behavioralParametersDockWidget.setFont(font)
        self.behavioralParametersDockWidget.setFloating(True)
        self.behavioralParametersDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.behavioralParametersDockWidget.setObjectName("behavioralParametersDockWidget")
        self.dockWidgetContents_22 = QtWidgets.QWidget()
        self.dockWidgetContents_22.setObjectName("dockWidgetContents_22")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.dockWidgetContents_22)
        self.gridLayout_18.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_18.setSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents_22)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 403, 594))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.nonVerbalParameters = QtWidgets.QWidget()
        self.nonVerbalParameters.setObjectName("nonVerbalParameters")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.nonVerbalParameters)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_5 = QtWidgets.QGroupBox(self.nonVerbalParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_22.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_22.setSpacing(6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setSpacing(6)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_21.addWidget(self.label_2, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem, 0, 0, 1, 1)
        self.gestureOpennessSlider = QtWidgets.QSlider(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gestureOpennessSlider.sizePolicy().hasHeightForWidth())
        self.gestureOpennessSlider.setSizePolicy(sizePolicy)
        self.gestureOpennessSlider.setMinimum(0)
        self.gestureOpennessSlider.setMaximum(1)
        self.gestureOpennessSlider.setPageStep(1)
        self.gestureOpennessSlider.setProperty("value", 0)
        self.gestureOpennessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gestureOpennessSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gestureOpennessSlider.setObjectName("gestureOpennessSlider")
        self.gridLayout_21.addWidget(self.gestureOpennessSlider, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_21.addWidget(self.label_10, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.nonVerbalParameters)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_12.addWidget(self.line_5, 3, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.nonVerbalParameters)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_12.addWidget(self.line_10, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.nonVerbalParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_26.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_26.setSpacing(6)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setSpacing(6)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_25.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_25.addWidget(self.label_3, 0, 0, 1, 1)
        self.proxemicsSlider = QtWidgets.QSlider(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxemicsSlider.sizePolicy().hasHeightForWidth())
        self.proxemicsSlider.setSizePolicy(sizePolicy)
        self.proxemicsSlider.setMinimum(0)
        self.proxemicsSlider.setMaximum(10)
        self.proxemicsSlider.setPageStep(1)
        self.proxemicsSlider.setProperty("value", 5)
        self.proxemicsSlider.setSliderPosition(5)
        self.proxemicsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.proxemicsSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.proxemicsSlider.setTickInterval(2)
        self.proxemicsSlider.setObjectName("proxemicsSlider")
        self.gridLayout_25.addWidget(self.proxemicsSlider, 0, 1, 1, 1)
        self.proxemicsLcdNumber = QtWidgets.QLCDNumber(self.groupBox_7)
        self.proxemicsLcdNumber.setEnabled(True)
        self.proxemicsLcdNumber.setAutoFillBackground(False)
        self.proxemicsLcdNumber.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.proxemicsLcdNumber.setFrameShape(QtWidgets.QFrame.Panel)
        self.proxemicsLcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.proxemicsLcdNumber.setLineWidth(1)
        self.proxemicsLcdNumber.setSmallDecimalPoint(True)
        self.proxemicsLcdNumber.setProperty("value", 3.5)
        self.proxemicsLcdNumber.setObjectName("proxemicsLcdNumber")
        self.gridLayout_25.addWidget(self.proxemicsLcdNumber, 1, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.nonVerbalParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_20.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_20.setSpacing(6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setSpacing(6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_19.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_19.addWidget(self.label_13, 0, 3, 1, 1)
        self.gazePatternSlider = QtWidgets.QSlider(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gazePatternSlider.sizePolicy().hasHeightForWidth())
        self.gazePatternSlider.setSizePolicy(sizePolicy)
        self.gazePatternSlider.setMaximum(1)
        self.gazePatternSlider.setPageStep(1)
        self.gazePatternSlider.setProperty("value", 0)
        self.gazePatternSlider.setSliderPosition(0)
        self.gazePatternSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gazePatternSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gazePatternSlider.setObjectName("gazePatternSlider")
        self.gridLayout_19.addWidget(self.gazePatternSlider, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem3, 0, 4, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.nonVerbalParameters, "")
        self.voiceParameters = QtWidgets.QWidget()
        self.voiceParameters.setObjectName("voiceParameters")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.voiceParameters)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_6 = QtWidgets.QGroupBox(self.voiceParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_24.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_24.setSpacing(6)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setSpacing(6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_23.addWidget(self.label_19, 3, 4, 1, 1)
        self.voiceProsodySlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voiceProsodySlider.sizePolicy().hasHeightForWidth())
        self.voiceProsodySlider.setSizePolicy(sizePolicy)
        self.voiceProsodySlider.setMinimum(0)
        self.voiceProsodySlider.setMaximum(1)
        self.voiceProsodySlider.setSingleStep(1)
        self.voiceProsodySlider.setPageStep(1)
        self.voiceProsodySlider.setProperty("value", 0)
        self.voiceProsodySlider.setOrientation(QtCore.Qt.Horizontal)
        self.voiceProsodySlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.voiceProsodySlider.setTickInterval(1)
        self.voiceProsodySlider.setObjectName("voiceProsodySlider")
        self.gridLayout_23.addWidget(self.voiceProsodySlider, 5, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_23.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_23.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_23.addWidget(self.label_14, 1, 0, 1, 1)
        self.voiceSpeedSlider = QtWidgets.QSlider(self.groupBox_6)
        self.voiceSpeedSlider.setMinimum(-4)
        self.voiceSpeedSlider.setMaximum(4)
        self.voiceSpeedSlider.setPageStep(1)
        self.voiceSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.voiceSpeedSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.voiceSpeedSlider.setTickInterval(2)
        self.voiceSpeedSlider.setObjectName("voiceSpeedSlider")
        self.gridLayout_23.addWidget(self.voiceSpeedSlider, 3, 1, 1, 3)
        self.voiceSpeedLabel = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voiceSpeedLabel.sizePolicy().hasHeightForWidth())
        self.voiceSpeedLabel.setSizePolicy(sizePolicy)
        self.voiceSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voiceSpeedLabel.setObjectName("voiceSpeedLabel")
        self.gridLayout_23.addWidget(self.voiceSpeedLabel, 2, 1, 1, 3)
        self.voicePitchSlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voicePitchSlider.sizePolicy().hasHeightForWidth())
        self.voicePitchSlider.setSizePolicy(sizePolicy)
        self.voicePitchSlider.setMinimum(-4)
        self.voicePitchSlider.setMaximum(4)
        self.voicePitchSlider.setSingleStep(1)
        self.voicePitchSlider.setPageStep(1)
        self.voicePitchSlider.setProperty("value", 0)
        self.voicePitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.voicePitchSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.voicePitchSlider.setTickInterval(2)
        self.voicePitchSlider.setObjectName("voicePitchSlider")
        self.gridLayout_23.addWidget(self.voicePitchSlider, 1, 1, 1, 3)
        self.voicePitchLabel = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voicePitchLabel.sizePolicy().hasHeightForWidth())
        self.voicePitchLabel.setSizePolicy(sizePolicy)
        self.voicePitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voicePitchLabel.setObjectName("voicePitchLabel")
        self.gridLayout_23.addWidget(self.voicePitchLabel, 0, 1, 1, 3)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_23.addWidget(self.label_15, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem4, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem5, 4, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_23.addWidget(self.label_16, 5, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_23.addWidget(self.label_17, 5, 3, 1, 2)
        self.gridLayout_24.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_6, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.voiceParameters, "")
        self.eyeColorParameters = QtWidgets.QWidget()
        self.eyeColorParameters.setObjectName("eyeColorParameters")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.eyeColorParameters)
        self.gridLayout_15.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox = QtWidgets.QGroupBox(self.eyeColorParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.greenEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.greenEyeColorRadioButton.setObjectName("greenEyeColorRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(DialogGUI)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.greenEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.greenEyeColorRadioButton, 1, 0, 1, 1)
        self.blueEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.blueEyeColorRadioButton.setObjectName("blueEyeColorRadioButton")
        self.buttonGroup.addButton(self.blueEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.blueEyeColorRadioButton, 1, 1, 1, 1)
        self.redEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.redEyeColorRadioButton.setObjectName("redEyeColorRadioButton")
        self.buttonGroup.addButton(self.redEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.redEyeColorRadioButton, 0, 1, 1, 1)
        self.whiteEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.whiteEyeColorRadioButton.setChecked(True)
        self.whiteEyeColorRadioButton.setObjectName("whiteEyeColorRadioButton")
        self.buttonGroup.addButton(self.whiteEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.whiteEyeColorRadioButton, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 212, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.eyeColorParameters, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setSpacing(6)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.behavioralParametersApplyButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.behavioralParametersApplyButton.setObjectName("behavioralParametersApplyButton")
        self.gridLayout_28.addWidget(self.behavioralParametersApplyButton, 1, 1, 1, 1)
        self.warningLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.warningLabel.setFont(font)
        self.warningLabel.setStyleSheet("color: rgb(236, 236, 236);")
        self.warningLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.warningLabel.setObjectName("warningLabel")
        self.gridLayout_28.addWidget(self.warningLabel, 0, 0, 1, 2)
        self.testBehavioralParametersButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.testBehavioralParametersButton.setEnabled(False)
        self.testBehavioralParametersButton.setObjectName("testBehavioralParametersButton")
        self.gridLayout_28.addWidget(self.testBehavioralParametersButton, 1, 0, 1, 1)
        self.behavioralParametersApplyComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.behavioralParametersApplyComboBox.setObjectName("behavioralParametersApplyComboBox")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.gridLayout_28.addWidget(self.behavioralParametersApplyComboBox, 2, 0, 1, 1)
        self.behavioralParametersApplyToAllButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.behavioralParametersApplyToAllButton.setObjectName("behavioralParametersApplyToAllButton")
        self.gridLayout_28.addWidget(self.behavioralParametersApplyToAllButton, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_28)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.gridLayout_13.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_18.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.behavioralParametersDockWidget.setWidget(self.dockWidgetContents_22)
        DialogGUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.behavioralParametersDockWidget)
        self.blocksDockWidget = QtWidgets.QDockWidget(DialogGUI)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.blocksDockWidget.setFont(font)
        self.blocksDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.blocksDockWidget.setObjectName("blocksDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_11 = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.dialogueBlocksCategoryComboBox = QtWidgets.QComboBox(self.groupBox_11)
        self.dialogueBlocksCategoryComboBox.setObjectName("dialogueBlocksCategoryComboBox")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.gridLayout_7.addWidget(self.dialogueBlocksCategoryComboBox, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_11)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 1, 0, 1, 1)
        self.dragListWidget = QtWidgets.QListWidget(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dragListWidget.setFont(font)
        self.dragListWidget.setLineWidth(1)
        self.dragListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.dragListWidget.setDragEnabled(True)
        self.dragListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.dragListWidget.setAlternatingRowColors(True)
        self.dragListWidget.setIconSize(QtCore.QSize(100, 60))
        self.dragListWidget.setWordWrap(True)
        self.dragListWidget.setSelectionRectVisible(True)
        self.dragListWidget.setObjectName("dragListWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/hreresources/pepper-icons/pepper-greet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.dragListWidget.addItem(item)
        self.gridLayout_7.addWidget(self.dragListWidget, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_11, 0, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.blocksDockWidget.setWidget(self.dockWidgetContents)
        DialogGUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.blocksDockWidget)
        self.logsDockWidget = QtWidgets.QDockWidget(DialogGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logsDockWidget.sizePolicy().hasHeightForWidth())
        self.logsDockWidget.setSizePolicy(sizePolicy)
        self.logsDockWidget.setMinimumSize(QtCore.QSize(182, 177))
        self.logsDockWidget.setFloating(False)
        self.logsDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.logsDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.logsDockWidget.setObjectName("logsDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_27.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_27.setSpacing(6)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.logsTextEdit = QtWidgets.QTextEdit(self.dockWidgetContents_2)
        self.logsTextEdit.setAcceptDrops(False)
        self.logsTextEdit.setAutoFillBackground(True)
        self.logsTextEdit.setStyleSheet("background: rgb(76, 76, 76)")
        self.logsTextEdit.setUndoRedoEnabled(False)
        self.logsTextEdit.setReadOnly(True)
        self.logsTextEdit.setAcceptRichText(True)
        self.logsTextEdit.setObjectName("logsTextEdit")
        self.gridLayout_27.addWidget(self.logsTextEdit, 0, 0, 1, 1)
        self.logsDockWidget.setWidget(self.dockWidgetContents_2)
        DialogGUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.logsDockWidget)
        self.musicDockWidget = QtWidgets.QDockWidget(DialogGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.musicDockWidget.sizePolicy().hasHeightForWidth())
        self.musicDockWidget.setSizePolicy(sizePolicy)
        self.musicDockWidget.setObjectName("musicDockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem9, 2, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.musicPlaylistComboBox = QtWidgets.QComboBox(self.dockWidgetContents_3)
        self.musicPlaylistComboBox.setObjectName("musicPlaylistComboBox")
        self.gridLayout_10.addWidget(self.musicPlaylistComboBox, 0, 1, 1, 1)
        self.musicTracksComboBox = QtWidgets.QComboBox(self.dockWidgetContents_3)
        self.musicTracksComboBox.setObjectName("musicTracksComboBox")
        self.gridLayout_10.addWidget(self.musicTracksComboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.musicPauseButton = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.musicPauseButton.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hreresources/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.musicPauseButton.setIcon(icon1)
        self.musicPauseButton.setObjectName("musicPauseButton")
        self.gridLayout_9.addWidget(self.musicPauseButton, 0, 1, 1, 1)
        self.musicPlayButton = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.musicPlayButton.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hreresources/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.musicPlayButton.setIcon(icon2)
        self.musicPlayButton.setObjectName("musicPlayButton")
        self.gridLayout_9.addWidget(self.musicPlayButton, 0, 2, 1, 1)
        self.musicMessageLineEdit = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.musicMessageLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.musicMessageLineEdit.setAutoFillBackground(False)
        self.musicMessageLineEdit.setStyleSheet("background-color: transparent;")
        self.musicMessageLineEdit.setText("")
        self.musicMessageLineEdit.setFrame(False)
        self.musicMessageLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.musicMessageLineEdit.setReadOnly(True)
        self.musicMessageLineEdit.setObjectName("musicMessageLineEdit")
        self.gridLayout_9.addWidget(self.musicMessageLineEdit, 2, 0, 1, 4)
        self.musicVolumeSpinBox = QtWidgets.QSpinBox(self.dockWidgetContents_3)
        self.musicVolumeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.musicVolumeSpinBox.setMaximum(100)
        self.musicVolumeSpinBox.setSingleStep(5)
        self.musicVolumeSpinBox.setProperty("value", 70)
        self.musicVolumeSpinBox.setObjectName("musicVolumeSpinBox")
        self.gridLayout_9.addWidget(self.musicVolumeSpinBox, 1, 2, 1, 1)
        self.musicVolumeButton = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.musicVolumeButton.setEnabled(False)
        self.musicVolumeButton.setObjectName("musicVolumeButton")
        self.gridLayout_9.addWidget(self.musicVolumeButton, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.musicDockWidget.setWidget(self.dockWidgetContents_3)
        DialogGUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.musicDockWidget)
        self.actionReload = QtWidgets.QAction(DialogGUI)
        self.actionReload.setCheckable(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/hreresources/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon3)
        self.actionReload.setObjectName("actionReload")
        self.actionMenuNew = QtWidgets.QAction(DialogGUI)
        self.actionMenuNew.setObjectName("actionMenuNew")
        self.actionMenuImportBlocks = QtWidgets.QAction(DialogGUI)
        self.actionMenuImportBlocks.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/hreresources/icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuImportBlocks.setIcon(icon4)
        self.actionMenuImportBlocks.setObjectName("actionMenuImportBlocks")
        self.actionMenuExportBlocks = QtWidgets.QAction(DialogGUI)
        self.actionMenuExportBlocks.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/hreresources/icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuExportBlocks.setIcon(icon5)
        self.actionMenuExportBlocks.setObjectName("actionMenuExportBlocks")
        self.actionMenuSave = QtWidgets.QAction(DialogGUI)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/hreresources/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuSave.setIcon(icon6)
        self.actionMenuSave.setObjectName("actionMenuSave")
        self.actionMenuSaveAs = QtWidgets.QAction(DialogGUI)
        self.actionMenuSaveAs.setIcon(icon6)
        self.actionMenuSaveAs.setObjectName("actionMenuSaveAs")
        self.actionMenuExit = QtWidgets.QAction(DialogGUI)
        self.actionMenuExit.setObjectName("actionMenuExit")
        self.actionMenuUndo = QtWidgets.QAction(DialogGUI)
        self.actionMenuUndo.setEnabled(True)
        self.actionMenuUndo.setObjectName("actionMenuUndo")
        self.actionMenuRedo = QtWidgets.QAction(DialogGUI)
        self.actionMenuRedo.setEnabled(True)
        self.actionMenuRedo.setObjectName("actionMenuRedo")
        self.actionMenuCopy = QtWidgets.QAction(DialogGUI)
        self.actionMenuCopy.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/hreresources/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuCopy.setIcon(icon7)
        self.actionMenuCopy.setObjectName("actionMenuCopy")
        self.actionMenuPaste = QtWidgets.QAction(DialogGUI)
        self.actionMenuPaste.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/hreresources/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuPaste.setIcon(icon8)
        self.actionMenuPaste.setObjectName("actionMenuPaste")
        self.actionMenuPasteParameters = QtWidgets.QAction(DialogGUI)
        self.actionMenuPasteParameters.setEnabled(False)
        self.actionMenuPasteParameters.setIcon(icon8)
        self.actionMenuPasteParameters.setObjectName("actionMenuPasteParameters")
        self.actionMenuDelete = QtWidgets.QAction(DialogGUI)
        self.actionMenuDelete.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/hreresources/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuDelete.setIcon(icon9)
        self.actionMenuDelete.setObjectName("actionMenuDelete")
        self.actionMenuClear = QtWidgets.QAction(DialogGUI)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/hreresources/icons/erase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuClear.setIcon(icon10)
        self.actionMenuClear.setObjectName("actionMenuClear")
        self.actionMenuConnect = QtWidgets.QAction(DialogGUI)
        self.actionMenuConnect.setEnabled(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/hreresources/icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuConnect.setIcon(icon11)
        self.actionMenuConnect.setObjectName("actionMenuConnect")
        self.actionMenuDisconnect = QtWidgets.QAction(DialogGUI)
        self.actionMenuDisconnect.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/hreresources/icons/disconnect1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuDisconnect.setIcon(icon12)
        self.actionMenuDisconnect.setObjectName("actionMenuDisconnect")
        self.actionMenuWakeUp = QtWidgets.QAction(DialogGUI)
        self.actionMenuWakeUp.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/hreresources/icons/eyeon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuWakeUp.setIcon(icon13)
        self.actionMenuWakeUp.setObjectName("actionMenuWakeUp")
        self.actionMenuRest = QtWidgets.QAction(DialogGUI)
        self.actionMenuRest.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/hreresources/icons/eyeoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuRest.setIcon(icon14)
        self.actionMenuRest.setObjectName("actionMenuRest")
        self.actionMenuEnableTouch = QtWidgets.QAction(DialogGUI)
        self.actionMenuEnableTouch.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/hreresources/icons/touch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuEnableTouch.setIcon(icon15)
        self.actionMenuEnableTouch.setObjectName("actionMenuEnableTouch")
        self.actionMenuShowImage = QtWidgets.QAction(DialogGUI)
        self.actionMenuShowImage.setEnabled(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/hreresources/icons/tablet-show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuShowImage.setIcon(icon16)
        self.actionMenuShowImage.setObjectName("actionMenuShowImage")
        self.actionMenuHideImage = QtWidgets.QAction(DialogGUI)
        self.actionMenuHideImage.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/hreresources/icons/tablet-hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuHideImage.setIcon(icon17)
        self.actionMenuHideImage.setObjectName("actionMenuHideImage")
        self.actionMenuVolumeUp = QtWidgets.QAction(DialogGUI)
        self.actionMenuVolumeUp.setEnabled(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/hreresources/icons/volume-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuVolumeUp.setIcon(icon18)
        self.actionMenuVolumeUp.setObjectName("actionMenuVolumeUp")
        self.actionMenuVolumeDown = QtWidgets.QAction(DialogGUI)
        self.actionMenuVolumeDown.setEnabled(False)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/hreresources/icons/volume-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuVolumeDown.setIcon(icon19)
        self.actionMenuVolumeDown.setObjectName("actionMenuVolumeDown")
        self.actionMenuTest = QtWidgets.QAction(DialogGUI)
        self.actionMenuTest.setEnabled(False)
        self.actionMenuTest.setObjectName("actionMenuTest")
        self.actionMenuPlay = QtWidgets.QAction(DialogGUI)
        self.actionMenuPlay.setEnabled(False)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/hreresources/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuPlay.setIcon(icon20)
        self.actionMenuPlay.setObjectName("actionMenuPlay")
        self.actionMenuPause = QtWidgets.QAction(DialogGUI)
        self.actionMenuPause.setEnabled(False)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/hreresources/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuPause.setIcon(icon21)
        self.actionMenuPause.setObjectName("actionMenuPause")
        self.actionMenuStop = QtWidgets.QAction(DialogGUI)
        self.actionMenuStop.setEnabled(False)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/hreresources/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuStop.setIcon(icon22)
        self.actionMenuStop.setObjectName("actionMenuStop")
        self.actionMenuEnableMoving = QtWidgets.QAction(DialogGUI)
        self.actionMenuEnableMoving.setEnabled(False)
        self.actionMenuEnableMoving.setObjectName("actionMenuEnableMoving")
        self.actionMenuDisableMoving = QtWidgets.QAction(DialogGUI)
        self.actionMenuDisableMoving.setEnabled(False)
        self.actionMenuDisableMoving.setObjectName("actionMenuDisableMoving")
        self.actionMenuDatabaseConnect = QtWidgets.QAction(DialogGUI)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/hreresources/icons/database-connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuDatabaseConnect.setIcon(icon23)
        self.actionMenuDatabaseConnect.setObjectName("actionMenuDatabaseConnect")
        self.actionMenuDatabaseDisconnect = QtWidgets.QAction(DialogGUI)
        self.actionMenuDatabaseDisconnect.setEnabled(False)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/hreresources/icons/database-disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuDatabaseDisconnect.setIcon(icon24)
        self.actionMenuDatabaseDisconnect.setObjectName("actionMenuDatabaseDisconnect")
        self.actionMenuZoomIn = QtWidgets.QAction(DialogGUI)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/hreresources/icons/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuZoomIn.setIcon(icon25)
        self.actionMenuZoomIn.setObjectName("actionMenuZoomIn")
        self.actionMenuZoomOut = QtWidgets.QAction(DialogGUI)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/hreresources/icons/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuZoomOut.setIcon(icon26)
        self.actionMenuZoomOut.setObjectName("actionMenuZoomOut")
        self.actionMenuBlockList = QtWidgets.QAction(DialogGUI)
        self.actionMenuBlockList.setObjectName("actionMenuBlockList")
        self.actionMenuLogs = QtWidgets.QAction(DialogGUI)
        self.actionMenuLogs.setObjectName("actionMenuLogs")
        self.actionMenuSimulate = QtWidgets.QAction(DialogGUI)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/hreresources/icons/simulate-chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuSimulate.setIcon(icon27)
        self.actionMenuSimulate.setObjectName("actionMenuSimulate")
        self.actionMenuMusic = QtWidgets.QAction(DialogGUI)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/hreresources/icons/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuMusic.setIcon(icon28)
        self.actionMenuMusic.setObjectName("actionMenuMusic")
        self.actionMenuMusicDockView = QtWidgets.QAction(DialogGUI)
        self.actionMenuMusicDockView.setObjectName("actionMenuMusicDockView")
        self.actionMenuSimulationDockView = QtWidgets.QAction(DialogGUI)
        self.actionMenuSimulationDockView.setObjectName("actionMenuSimulationDockView")
        self.menuFile.addAction(self.actionMenuNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuImportBlocks)
        self.menuFile.addAction(self.actionMenuExportBlocks)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuSave)
        self.menuFile.addAction(self.actionMenuSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuMusic)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuExit)
        self.menuEdit.addAction(self.actionMenuUndo)
        self.menuEdit.addAction(self.actionMenuRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMenuCopy)
        self.menuEdit.addAction(self.actionMenuPaste)
        self.menuEdit.addAction(self.actionMenuPasteParameters)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMenuDelete)
        self.menuEdit.addAction(self.actionMenuClear)
        self.menuRobot.addAction(self.actionMenuConnect)
        self.menuRobot.addAction(self.actionMenuDisconnect)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuWakeUp)
        self.menuRobot.addAction(self.actionMenuRest)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuEnableTouch)
        self.menuRobot.addAction(self.actionMenuShowImage)
        self.menuRobot.addAction(self.actionMenuHideImage)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuVolumeUp)
        self.menuRobot.addAction(self.actionMenuVolumeDown)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuTest)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuPlay)
        self.menuRobot.addAction(self.actionMenuPause)
        self.menuRobot.addAction(self.actionMenuStop)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuSimulate)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuEnableMoving)
        self.menuRobot.addAction(self.actionMenuDisableMoving)
        self.menuDatabase.addAction(self.actionMenuDatabaseConnect)
        self.menuDatabase.addAction(self.actionMenuDatabaseDisconnect)
        self.menuView.addAction(self.actionMenuBlockList)
        self.menuView.addAction(self.actionMenuLogs)
        self.menuView.addAction(self.actionMenuSimulationDockView)
        self.menuView.addAction(self.actionMenuMusicDockView)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionMenuZoomIn)
        self.menuView.addAction(self.actionMenuZoomOut)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuRobot.menuAction())
        self.menuBar.addAction(self.menuDatabase.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.mainToolBar.addAction(self.actionMenuSave)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuCopy)
        self.mainToolBar.addAction(self.actionMenuPasteParameters)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuClear)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuConnect)
        self.mainToolBar.addAction(self.actionMenuDisconnect)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuWakeUp)
        self.mainToolBar.addAction(self.actionMenuRest)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuVolumeUp)
        self.mainToolBar.addAction(self.actionMenuVolumeDown)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuPlay)
        self.mainToolBar.addAction(self.actionMenuStop)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuMusic)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuSimulate)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuImportBlocks)

        self.retranslateUi(DialogGUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogGUI)

    def retranslateUi(self, DialogGUI):
        _translate = QtCore.QCoreApplication.translate
        DialogGUI.setWindowTitle(_translate("DialogGUI", "Interaction Design"))
        self.label_8.setText(_translate("DialogGUI", "DESIGN PANEL"))
        self.menuFile.setTitle(_translate("DialogGUI", "File"))
        self.menuEdit.setTitle(_translate("DialogGUI", "Edit"))
        self.menuRobot.setTitle(_translate("DialogGUI", "Robot"))
        self.menuDatabase.setTitle(_translate("DialogGUI", "Database"))
        self.menuView.setTitle(_translate("DialogGUI", "View"))
        self.behavioralParametersDockWidget.setWindowTitle(_translate("DialogGUI", "Behavioral Parameters"))
        self.groupBox_5.setTitle(_translate("DialogGUI", "Gesture Openness"))
        self.label_2.setText(_translate("DialogGUI", "Open"))
        self.label_10.setText(_translate("DialogGUI", "Close"))
        self.groupBox_7.setTitle(_translate("DialogGUI", "Proxemic Closeness"))
        self.label_4.setText(_translate("DialogGUI", "Far"))
        self.label_3.setText(_translate("DialogGUI", "Close"))
        self.groupBox_4.setTitle(_translate("DialogGUI", "Gaze Pattern"))
        self.label_12.setText(_translate("DialogGUI", "Fixated"))
        self.label_13.setText(_translate("DialogGUI", "Diverted"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nonVerbalParameters), _translate("DialogGUI", "Non-Verbal"))
        self.groupBox_6.setTitle(_translate("DialogGUI", "Voice"))
        self.label_19.setText(_translate("DialogGUI", "Fast"))
        self.label_18.setText(_translate("DialogGUI", "Slow"))
        self.label_6.setText(_translate("DialogGUI", "High"))
        self.label_14.setText(_translate("DialogGUI", "Low"))
        self.voiceSpeedLabel.setText(_translate("DialogGUI", "Speed"))
        self.voicePitchLabel.setText(_translate("DialogGUI", "Pitch"))
        self.label_15.setText(_translate("DialogGUI", "Prosody"))
        self.label_16.setText(_translate("DialogGUI", "Weak"))
        self.label_17.setText(_translate("DialogGUI", "Strong"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voiceParameters), _translate("DialogGUI", "Voice"))
        self.groupBox.setTitle(_translate("DialogGUI", "Eye Color"))
        self.greenEyeColorRadioButton.setText(_translate("DialogGUI", "Green"))
        self.blueEyeColorRadioButton.setText(_translate("DialogGUI", "Blue"))
        self.redEyeColorRadioButton.setText(_translate("DialogGUI", "Red"))
        self.whiteEyeColorRadioButton.setText(_translate("DialogGUI", "White"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eyeColorParameters), _translate("DialogGUI", "Eyes"))
        self.behavioralParametersApplyButton.setText(_translate("DialogGUI", "Apply"))
        self.warningLabel.setText(_translate("DialogGUI", "Click \'Apply\' to save the changes."))
        self.testBehavioralParametersButton.setText(_translate("DialogGUI", "Test"))
        self.behavioralParametersApplyComboBox.setItemText(0, _translate("DialogGUI", "All Parameters"))
        self.behavioralParametersApplyComboBox.setItemText(1, _translate("DialogGUI", "Gesture Openness"))
        self.behavioralParametersApplyComboBox.setItemText(2, _translate("DialogGUI", "Gaze Pattern"))
        self.behavioralParametersApplyComboBox.setItemText(3, _translate("DialogGUI", "Proxemic Closeness"))
        self.behavioralParametersApplyComboBox.setItemText(4, _translate("DialogGUI", "Voice"))
        self.behavioralParametersApplyComboBox.setItemText(5, _translate("DialogGUI", "Eye Color"))
        self.behavioralParametersApplyToAllButton.setText(_translate("DialogGUI", "Apply to All"))
        self.blocksDockWidget.setWindowTitle(_translate("DialogGUI", "Dialogue Blocks"))
        self.dialogueBlocksCategoryComboBox.setItemText(0, _translate("DialogGUI", "All"))
        self.dialogueBlocksCategoryComboBox.setItemText(1, _translate("DialogGUI", "Opening"))
        self.dialogueBlocksCategoryComboBox.setItemText(2, _translate("DialogGUI", "Service-Provision"))
        self.dialogueBlocksCategoryComboBox.setItemText(3, _translate("DialogGUI", "Closing"))
        self.dialogueBlocksCategoryComboBox.setItemText(4, _translate("DialogGUI", "Chit-Chat"))
        self.dragListWidget.setSortingEnabled(True)
        __sortingEnabled = self.dragListWidget.isSortingEnabled()
        self.dragListWidget.setSortingEnabled(False)
        item = self.dragListWidget.item(0)
        item.setText(_translate("DialogGUI", "Salutation"))
        self.dragListWidget.setSortingEnabled(__sortingEnabled)
        self.logsDockWidget.setWindowTitle(_translate("DialogGUI", "Logs"))
        self.musicDockWidget.setWindowTitle(_translate("DialogGUI", "Music Player"))
        self.label.setText(_translate("DialogGUI", "Playlists"))
        self.label_5.setText(_translate("DialogGUI", "Tracks"))
        self.musicPauseButton.setText(_translate("DialogGUI", "Pause"))
        self.musicPlayButton.setText(_translate("DialogGUI", "Play"))
        self.musicVolumeButton.setText(_translate("DialogGUI", "Vol (%)"))
        self.actionReload.setText(_translate("DialogGUI", "Reload"))
        self.actionReload.setToolTip(_translate("DialogGUI", "Reload"))
        self.actionMenuNew.setText(_translate("DialogGUI", "New"))
        self.actionMenuNew.setShortcut(_translate("DialogGUI", "Ctrl+N"))
        self.actionMenuImportBlocks.setText(_translate("DialogGUI", "Import Design"))
        self.actionMenuImportBlocks.setToolTip(_translate("DialogGUI", "Import Design"))
        self.actionMenuExportBlocks.setText(_translate("DialogGUI", "Export Design"))
        self.actionMenuExportBlocks.setToolTip(_translate("DialogGUI", "Export Design"))
        self.actionMenuSave.setText(_translate("DialogGUI", "Save"))
        self.actionMenuSave.setShortcut(_translate("DialogGUI", "Ctrl+S"))
        self.actionMenuSaveAs.setText(_translate("DialogGUI", "Save As"))
        self.actionMenuSaveAs.setShortcut(_translate("DialogGUI", "Ctrl+Shift+S"))
        self.actionMenuExit.setText(_translate("DialogGUI", "Exit"))
        self.actionMenuExit.setShortcut(_translate("DialogGUI", "Ctrl+Q"))
        self.actionMenuUndo.setText(_translate("DialogGUI", "Undo"))
        self.actionMenuUndo.setShortcut(_translate("DialogGUI", "Ctrl+Z"))
        self.actionMenuRedo.setText(_translate("DialogGUI", "Redo"))
        self.actionMenuRedo.setShortcut(_translate("DialogGUI", "Ctrl+Shift+Z"))
        self.actionMenuCopy.setText(_translate("DialogGUI", "Copy"))
        self.actionMenuCopy.setShortcut(_translate("DialogGUI", "Ctrl+C"))
        self.actionMenuPaste.setText(_translate("DialogGUI", "Paste"))
        self.actionMenuPaste.setShortcut(_translate("DialogGUI", "Ctrl+V"))
        self.actionMenuPasteParameters.setText(_translate("DialogGUI", "Paste Parameters"))
        self.actionMenuPasteParameters.setToolTip(_translate("DialogGUI", "Paste Parameters"))
        self.actionMenuPasteParameters.setShortcut(_translate("DialogGUI", "Ctrl+Shift+V"))
        self.actionMenuDelete.setText(_translate("DialogGUI", "Delete"))
        self.actionMenuDelete.setShortcut(_translate("DialogGUI", "Backspace"))
        self.actionMenuClear.setText(_translate("DialogGUI", "Clear"))
        self.actionMenuClear.setShortcut(_translate("DialogGUI", "Ctrl+Shift+Backspace"))
        self.actionMenuConnect.setText(_translate("DialogGUI", "Connect"))
        self.actionMenuDisconnect.setText(_translate("DialogGUI", "Disconnect"))
        self.actionMenuWakeUp.setText(_translate("DialogGUI", "Wake Up"))
        self.actionMenuRest.setText(_translate("DialogGUI", "Rest"))
        self.actionMenuEnableTouch.setText(_translate("DialogGUI", "Enable Touch"))
        self.actionMenuShowImage.setText(_translate("DialogGUI", "Show Image"))
        self.actionMenuHideImage.setText(_translate("DialogGUI", "Hide Image"))
        self.actionMenuVolumeUp.setText(_translate("DialogGUI", "Vol+"))
        self.actionMenuVolumeDown.setText(_translate("DialogGUI", "Vol-"))
        self.actionMenuTest.setText(_translate("DialogGUI", "Test"))
        self.actionMenuPlay.setText(_translate("DialogGUI", "Play"))
        self.actionMenuPause.setText(_translate("DialogGUI", "Pause"))
        self.actionMenuStop.setText(_translate("DialogGUI", "Stop"))
        self.actionMenuEnableMoving.setText(_translate("DialogGUI", "Enable Moving"))
        self.actionMenuDisableMoving.setText(_translate("DialogGUI", "Disable Moving"))
        self.actionMenuDatabaseConnect.setText(_translate("DialogGUI", "Connect"))
        self.actionMenuDatabaseDisconnect.setText(_translate("DialogGUI", "Disconnect"))
        self.actionMenuZoomIn.setText(_translate("DialogGUI", "Zoom In"))
        self.actionMenuZoomIn.setShortcut(_translate("DialogGUI", "Ctrl+="))
        self.actionMenuZoomOut.setText(_translate("DialogGUI", "Zoom Out"))
        self.actionMenuZoomOut.setToolTip(_translate("DialogGUI", "Zoom Out"))
        self.actionMenuZoomOut.setShortcut(_translate("DialogGUI", "Ctrl+-"))
        self.actionMenuBlockList.setText(_translate("DialogGUI", "Block List Panel"))
        self.actionMenuLogs.setText(_translate("DialogGUI", "Logs Panel"))
        self.actionMenuSimulate.setText(_translate("DialogGUI", "Simulate"))
        self.actionMenuMusic.setText(_translate("DialogGUI", "Spotify"))
        self.actionMenuMusic.setToolTip(_translate("DialogGUI", "Music"))
        self.actionMenuMusicDockView.setText(_translate("DialogGUI", "Music Panel"))
        self.actionMenuSimulationDockView.setText(_translate("DialogGUI", "Simulation Panel"))
        self.actionMenuSimulationDockView.setToolTip(_translate("DialogGUI", "Simulation"))


import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogGUI = QtWidgets.QMainWindow()
    ui = Ui_DialogGUI()
    ui.setupUi(DialogGUI)
    DialogGUI.show()
    sys.exit(app.exec_())
