# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interaction_manager/ui/editblockdialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditBlockDialog(object):
    def setupUi(self, EditBlockDialog):
        EditBlockDialog.setObjectName("EditBlockDialog")
        EditBlockDialog.resize(449, 542)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditBlockDialog.sizePolicy().hasHeightForWidth())
        EditBlockDialog.setSizePolicy(sizePolicy)
        EditBlockDialog.setMinimumSize(QtCore.QSize(0, 0))
        EditBlockDialog.setMaximumSize(QtCore.QSize(750, 750))
        self.gridLayout_8 = QtWidgets.QGridLayout(EditBlockDialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(EditBlockDialog)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.propertiesTab = QtWidgets.QWidget()
        self.propertiesTab.setObjectName("propertiesTab")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.propertiesTab)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.blockDescriptionLineEdit = QtWidgets.QLineEdit(self.propertiesTab)
        self.blockDescriptionLineEdit.setObjectName("blockDescriptionLineEdit")
        self.gridLayout_2.addWidget(self.blockDescriptionLineEdit, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.propertiesTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.propertiesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.patternLineEdit = QtWidgets.QLineEdit(self.propertiesTab)
        self.patternLineEdit.setEnabled(False)
        self.patternLineEdit.setObjectName("patternLineEdit")
        self.gridLayout_2.addWidget(self.patternLineEdit, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.propertiesTab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_13.addWidget(self.line_9, 3, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.propertiesTab)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_13.addWidget(self.line_10, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.propertiesTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.messageTypeComboBox = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageTypeComboBox.sizePolicy().hasHeightForWidth())
        self.messageTypeComboBox.setSizePolicy(sizePolicy)
        self.messageTypeComboBox.setObjectName("messageTypeComboBox")
        self.messageTypeComboBox.addItem("")
        self.messageTypeComboBox.addItem("")
        self.gridLayout_19.addWidget(self.messageTypeComboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_19.addWidget(self.label, 0, 0, 1, 1)
        self.messageTextEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.messageTextEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.messageTextEdit.setMaximumSize(QtCore.QSize(16777215, 200))
        self.messageTextEdit.setObjectName("messageTextEdit")
        self.gridLayout_19.addWidget(self.messageTextEdit, 1, 0, 1, 2)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.propertiesTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 3, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.groupBox_4)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_12.addWidget(self.line_8, 2, 1, 1, 1)
        self.closeGestureLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.closeGestureLineEdit.setObjectName("closeGestureLineEdit")
        self.gridLayout_12.addWidget(self.closeGestureLineEdit, 3, 1, 1, 1)
        self.openGestureLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.openGestureLineEdit.setObjectName("openGestureLineEdit")
        self.gridLayout_12.addWidget(self.openGestureLineEdit, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_12.addWidget(self.label_16, 0, 0, 1, 1)
        self.openGestureComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.openGestureComboBox.setObjectName("openGestureComboBox")
        self.gridLayout_12.addWidget(self.openGestureComboBox, 1, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_12.addWidget(self.line_3, 5, 1, 1, 1)
        self.closeGesturesComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.closeGesturesComboBox.setObjectName("closeGesturesComboBox")
        self.gridLayout_12.addWidget(self.closeGesturesComboBox, 4, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.propertiesTab, "")
        self.topicTab = QtWidgets.QWidget()
        self.topicTab.setObjectName("topicTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.topicTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.topicNameComboBox = QtWidgets.QComboBox(self.topicTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.topicNameComboBox.setFont(font)
        self.topicNameComboBox.setObjectName("topicNameComboBox")
        self.topicNameComboBox.addItem("")
        self.topicNameComboBox.addItem("")
        self.topicNameComboBox.addItem("")
        self.gridLayout_5.addWidget(self.topicNameComboBox, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.topicTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.topicTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 2, 1, 1)
        self.topicTagComboBox = QtWidgets.QComboBox(self.topicTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topicTagComboBox.sizePolicy().hasHeightForWidth())
        self.topicTagComboBox.setSizePolicy(sizePolicy)
        self.topicTagComboBox.setObjectName("topicTagComboBox")
        self.gridLayout_5.addWidget(self.topicTagComboBox, 0, 3, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.topicTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.feedback2TextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.feedback2TextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feedback2TextEdit.sizePolicy().hasHeightForWidth())
        self.feedback2TextEdit.setSizePolicy(sizePolicy)
        self.feedback2TextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.feedback2TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.feedback2TextEdit.setObjectName("feedback2TextEdit")
        self.gridLayout_3.addWidget(self.feedback2TextEdit, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 7, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.answer1TextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.answer1TextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.answer1TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.answer1TextEdit.setObjectName("answer1TextEdit")
        self.gridLayout_3.addWidget(self.answer1TextEdit, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 3, 0, 1, 2)
        self.feedback1TextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.feedback1TextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.feedback1TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.feedback1TextEdit.setObjectName("feedback1TextEdit")
        self.gridLayout_3.addWidget(self.feedback1TextEdit, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 9, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(51, 51, 51);")
        self.label_18.setScaledContents(True)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.gridLayout_14.addWidget(self.label_18, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_14, 8, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.answer2TextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.answer2TextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer2TextEdit.sizePolicy().hasHeightForWidth())
        self.answer2TextEdit.setSizePolicy(sizePolicy)
        self.answer2TextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.answer2TextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.answer2TextEdit.setObjectName("answer2TextEdit")
        self.gridLayout_3.addWidget(self.answer2TextEdit, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.answer1GoToComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.answer1GoToComboBox.setObjectName("answer1GoToComboBox")
        self.gridLayout.addWidget(self.answer1GoToComboBox, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.answer2GoToComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.answer2GoToComboBox.setObjectName("answer2GoToComboBox")
        self.gridLayout_6.addWidget(self.answer2GoToComboBox, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 6, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.topicTab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_10.addWidget(self.line_7, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.topicTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_10.addWidget(self.line_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.topicTab, "")
        self.tabletTab = QtWidgets.QWidget()
        self.tabletTab.setObjectName("tabletTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabletTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabletTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.tabletPageNameComboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabletPageNameComboBox.sizePolicy().hasHeightForWidth())
        self.tabletPageNameComboBox.setSizePolicy(sizePolicy)
        self.tabletPageNameComboBox.setObjectName("tabletPageNameComboBox")
        self.tabletPageNameComboBox.addItem("")
        self.tabletPageNameComboBox.addItem("")
        self.tabletPageNameComboBox.addItem("")
        self.tabletPageNameComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tabletPageNameComboBox)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.tabletImageComboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabletImageComboBox.sizePolicy().hasHeightForWidth())
        self.tabletImageComboBox.setSizePolicy(sizePolicy)
        self.tabletImageComboBox.setObjectName("tabletImageComboBox")
        self.tabletImageComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tabletImageComboBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.tabletHeadingTextEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.tabletHeadingTextEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.tabletHeadingTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tabletHeadingTextEdit.setObjectName("tabletHeadingTextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tabletHeadingTextEdit)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.tabletInfoTextEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.tabletInfoTextEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.tabletInfoTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tabletInfoTextEdit.setObjectName("tabletInfoTextEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tabletInfoTextEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabletTab, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditBlockDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_8.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(EditBlockDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(EditBlockDialog.reject)
        self.buttonBox.accepted.connect(EditBlockDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(EditBlockDialog)

    def retranslateUi(self, EditBlockDialog):
        _translate = QtCore.QCoreApplication.translate
        EditBlockDialog.setWindowTitle(_translate("EditBlockDialog", "Edit Block"))
        self.label_14.setText(_translate("EditBlockDialog", "Description"))
        self.label_2.setText(_translate("EditBlockDialog", "Pattern"))
        self.patternLineEdit.setPlaceholderText(_translate("EditBlockDialog", "Pattern"))
        self.groupBox_5.setTitle(_translate("EditBlockDialog", "Message"))
        self.messageTypeComboBox.setItemText(0, _translate("EditBlockDialog", "Informal"))
        self.messageTypeComboBox.setItemText(1, _translate("EditBlockDialog", "Formal"))
        self.label.setText(_translate("EditBlockDialog", "Type"))
        self.groupBox_4.setTitle(_translate("EditBlockDialog", "Gestures"))
        self.label_17.setText(_translate("EditBlockDialog", "Close Gesture"))
        self.label_16.setText(_translate("EditBlockDialog", "Open Gesture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.propertiesTab), _translate("EditBlockDialog", "Properties"))
        self.topicNameComboBox.setItemText(0, _translate("EditBlockDialog", "general"))
        self.topicNameComboBox.setItemText(1, _translate("EditBlockDialog", "index"))
        self.topicNameComboBox.setItemText(2, _translate("EditBlockDialog", "wellbeing"))
        self.label_11.setText(_translate("EditBlockDialog", "Topic"))
        self.label_12.setText(_translate("EditBlockDialog", "Tag"))
        self.groupBox_2.setTitle(_translate("EditBlockDialog", "Expected Answers"))
        self.label_4.setText(_translate("EditBlockDialog", "Robot Feedback #1"))
        self.label_5.setText(_translate("EditBlockDialog", "User Answer #2"))
        self.label_6.setText(_translate("EditBlockDialog", "Robot Feedback #2"))
        self.label_18.setText(_translate("EditBlockDialog", "Separate the answers by semicolon (;) to allow multiple options"))
        self.label_3.setText(_translate("EditBlockDialog", "User Answer #1"))
        self.label_13.setText(_translate("EditBlockDialog", "Go To"))
        self.label_15.setText(_translate("EditBlockDialog", "Go To"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.topicTab), _translate("EditBlockDialog", "Topic"))
        self.groupBox_3.setTitle(_translate("EditBlockDialog", "HTML Page"))
        self.label_9.setText(_translate("EditBlockDialog", "Name"))
        self.tabletPageNameComboBox.setItemText(0, _translate("EditBlockDialog", "index"))
        self.tabletPageNameComboBox.setItemText(1, _translate("EditBlockDialog", "displayinfo"))
        self.tabletPageNameComboBox.setItemText(2, _translate("EditBlockDialog", "confirmation"))
        self.tabletPageNameComboBox.setItemText(3, _translate("EditBlockDialog", "help"))
        self.label_8.setText(_translate("EditBlockDialog", "Image"))
        self.tabletImageComboBox.setItemText(0, _translate("EditBlockDialog", "pepper-standing.png"))
        self.label_7.setText(_translate("EditBlockDialog", "Heading"))
        self.label_10.setText(_translate("EditBlockDialog", "Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabletTab), _translate("EditBlockDialog", "Tablet"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditBlockDialog = QtWidgets.QDialog()
    ui = Ui_EditBlockDialog()
    ui.setupUi(EditBlockDialog)
    EditBlockDialog.show()
    sys.exit(app.exec_())
